name: Build and publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.10.0
        with:
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          pull: true
